name: Terraform Azure Deployment Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:

  terraform-init:
    name: Terraform Init Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

  terraform-validate:
    name: Terraform Validate Stage
    runs-on: ubuntu-latest
    needs: terraform-init

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        run: terraform validate

  terraform-plan:
    name: Terraform Plan Stage
    runs-on: ubuntu-latest
    needs: terraform-validate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply Stage
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: terraform apply -auto-approve
